import { notFound } from "next/navigation";
import { getProposals } from "@/lib/store";
import { resolveProposalForSlug, renderProposalArticleHTML } from "@/lib/proposalShared";
import PrintButton from "../PrintButton";

// Always resolve against the live database — this is a public, shareable
// link, so it must reflect the client's most recent proposal, not a
// build-time snapshot.
export const dynamic = "force-dynamic";

export default async function PublicProposalPage({
  params,
}: {
  params: { slug: string };
}) {
  const proposals = await getProposals();
  const proposal = resolveProposalForSlug(proposals as any[], params.slug);

  if (!proposal) {
    notFound();
  }

  const articleHtml = renderProposalArticleHTML(proposal);

  return (
    <div className="public-view-shell">
      <div className="public-view-topbar">
        <div className="brand">
          tulong<span className="dot"></span>
        </div>
        <PrintButton />
      </div>
      <div
        className="public-view-main"
        // Generated by the same trusted template as the internal tool's
        // doc view (renderProposalArticleHTML), from a stored proposal
        // record — not user-supplied markup at request time.
        dangerouslySetInnerHTML={{ __html: articleHtml }}
      />
    </div>
  );
}
